### PR TITLE
Update dependencies and add basic needed data to the snap

### PR DESCRIPTION
**Pull request by nohal**
- Add library dependencies for the current source tree state
- Include tide data, crude basemap and docs to make the UX comparable with normal installation.

### CODE REVIEW

**Comment by msis** [comment]
thanks @nohal !
I will compile again and merge.
PS: would you be interested in CI? I can setup a travis quickly too.

**Comment by nohal** [comment]
CI for the snap? How would it work?
If you talk about CI for the whole project, we already have both [travis](https://travis-ci.org/OpenCPN/OpenCPN) and [appveyor](https://ci.appveyor.com/project/bdbcat/opencpn) running.
Or extending our current travis builds so that it generates the snap from eg. tag builds? That IMO would be sweet...

**Comment by msis** [comment]
yes, I was thinking adding it to your existing travis. 
I can then reroute the snap build to your repo so it's all in one repo.
PS: I'm a bit busy now, it might take a bit before you see the PR.

**Comment by nohal** [comment]
OK, we survived without it until now, so I suppose there is no hurry :)

**Comment by nohal** [comment]
We have just tagged OpenCPN 4.8.2 release. Good moment for a "stable" snap...

**Comment by msis** [comment]
This is now is `develop` branch.
Starting a stable release branch with 4.8.2/

**Pull request closed without merging**
